### ISSUE TITLE
Setting up adafruit feed (please help with configuration

### ISSUE THREAD

**Issue by vschinazi** [roscoe81/enviro-monitor#4]
Hi Ross

I've spent a couple of hours trying to figure how to set up the adafruit io feed with the enviro+ and particle sensors and I feel I'm just a few settings away from getting this to work. I am attaching a couple of screenshots and will also describe what I have done. I would be very grateful if you could let me know why my feeds are not appearing in the io adafruit. 

1. I am using an pi zero with Enviro+ and the particle sensor.

2. I have edited the "Northcliff_adafruit_io_feed_setup_Gen.py" file with my details but I'm really not sure what to do with the aio_feed_prefix. I have edited that line to have only 1 property and one location. I have called these "Mermaid" and "Home". Everything else, I left as default. I have also added that package type (Basic Combo), my "aio_user_name" and "aio_key" (see screenshot 1).When I run this script, I get no errors and the feeds and dashboard are created in my io adafruit website (see screen shot 2).

3. I then edited my config.json file to include "enable_adafruit_io: true", my aio user name and aio key. I have also edited the "aio_houselhold_prefix" to correspond to "Mermaid" and the aio_location_prefix to correspond to "Home" but I feel that this is incorrect and I do not know what to add in these fields. Everything else I left as default but will eventually change the city name to "Gold Coast" and time zone to "Queensland" (see screen shot 3).

4. I have edited the config.json to point it in the folder where my edited config is located (see screen shot 4). I also do not get any errors when I run this script and the enviro+ monitor in my pi turn on and I can cycle through the different data types. 

I think the problem is just sending the feed to io adafruit but I am really not sure how to fix this. 
Please let me know what I am doing wrong. I am really excited to get this dashboard working.

Thanking you in advance,

Victor

![screenshot3](https://user-images.githubusercontent.com/2072586/85215568-f80cca00-b3bd-11ea-9537-5f5d6768f6b1.png)
![screenshot4](https://user-images.githubusercontent.com/2072586/85215572-fba05100-b3bd-11ea-8c9d-924a98eb8168.png)
![screenshot1](https://user-images.githubusercontent.com/2072586/85215573-fe9b4180-b3bd-11ea-869d-38183b39a430.png)
<img width="1377" alt="screenshot2" src="https://user-images.githubusercontent.com/2072586/85215574-05c24f80-b3be-11ea-9ce3-a07a305ebbc6.png">

**Comment by roscoe81** [comment]
Hi Victor. I've updated the README to provide more info on the Adafruit IO setup in response to your initial query. Have a look at that and, in the meantime, I'll look at your more detailed request.

**Comment by vschinazi** [comment]
Hi Ross

Thank you for the quick reply. I have adapted the setting as you describe. Again, I get no errors but the data does not seem to send. 
As I was adapting, it seems that something worked because I saw some values but it went away.  I have now reproduced it as you describe and still cannot see the values. Is it possible that it takes longer to load in IO adafruit?

Any suggestion would be really helpful.

Thank you very much for all your help. I feel I am almost there.

Kind regards,

Victor

**Comment by vschinazi** [comment]
Hi Ross,

I got it :) I am so happy about this. I can now get the premium package from adafruit IO and use the cooler and fancy display.

This is awesome :)

Thank you!

<img width="1387" alt="Screenshot 2020-06-21 at 14 02 35" src="https://user-images.githubusercontent.com/2072586/85216460-0b249780-b3c8-11ea-9e4a-f6f9634cee63.png">

**Comment by roscoe81** [comment]
Glad that you got it Vince. You also mentioned that you'll change the config.json to have "city_name": "Gold Coast" and "time_zone": "Australia/Queensland". If you do, you'll need to add a custom location to the "custom_locations" config data, so that the Astral database is updated. You can do that by changing it to read "custom_locations": ["Townsville, Australia, Queensland, -19.26639, 146.80569", "Gold Coast, Australia, Queensland, your latitude, your longitude"]. Let me know if that works.

**Comment by vschinazi** [comment]
Hi Ross

I’ll definitely try this. I am just letting it run now for the next hour so I can collect some data points and then I’ll make this change. So far I could only get the reading for temperature, humidity, pressure, Barometer and Forecast Icon. I could not see any of the readings for the gases and the PM sensor but I think it is a matter of time until the appear. I’ll let you know how that goes.

Thank you again for this incredible project. I really appreciate all the work you have put into this and also thank yo for your support!

Kind regards,

Victor


Victor Schinazi
Assistant Professor

Bond University

[Bond University]<https://www.vrschinazi.com/>  [Bond University] <https://twitter.com/vschinazi>       [Bond University] <https://www.linkedin.com/in/victor-schinazi-3223a725/>       [Bond University] <https://github.com/vschinazi>


A  Bond University | Gold Coast, Australia

T   +617 5595 2665<tel:+617%205595%202665>

E   victor_schinazi@bond.edu.au<mailto:victor_schinazi@bond.edu.au>

Virtual office:  https://bond.edu.au/collab-vschinaz

bond.edu.au/profile/victor-schinazi<http://bond.edu.au/profile/victor-schinazi>



[https://img.mysignature.io/pixel/887547/signature/144017]<https://mysignature.io/editor/?utm_source=expiredpixel>




On 21 Jun 2020, at 14:39, Ross Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:



Glad that you got it Vince. You also mentioned that you'll change the config.json to have "city_name": "Gold Coast" and "time_zone": "Australia/Queensland". If you do, you'll need to add a custom location to the "custom_locations" config data, so that the Astral database is updated. You can do that by changing it to read "custom_locations": ["Townsville, Australia, Queensland, -19.26639, 146.80569", "Gold Coast, Australia, Queensland, your latitude, your longitude"]. Let me know if that works.

**Comment by roscoe81** [comment]
The unit won't send gas feeds until the gas sensors complete their 100 minute warm-up time. It's strange about the particle feeds, they should be sent in the first available  feed window.

**Comment by vschinazi** [comment]
HI Ross

Particle feeds just showed up. Thank yo for letting me know about the gas calibration.
It seems everything is working and I have to learn to be more patient :)

One lat question, I ran the script from a python editor. I tried running from console but got an error. Is this common?

Thank you,

Victor

On 21 Jun 2020, at 14:53, Ross Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:



The unit won't send gas feeds until the gas sensors complete their 100 minute warm-up time. It's strange about the particle feeds, they should be sent in the first available feed window.

**Comment by roscoe81** [comment]
All I can think of is that you might not be running Python 3 from your console. You could try "python3 file_name" and see if that works.

**Comment by vschinazi** [comment]
Hi Ross

Yes. That’s correct :)
Thank yo python3 worked. As you can probably judge I am a bit of newbie here.

I am running from the console now and also made the changes to the city and coordinates. No errors there.

Thank you,

Victor

On 21 Jun 2020, at 15:00, Ross Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:



All I can think of is that you might not be running Python 3 from your console. You could try "python3 file_name" and see if that works.

**Comment by vschinazi** [comment]
Hi Ross

I just wanted to send you a link to my dashboard: https://io.adafruit.com/vschinazi/dashboards/home?kiosk=true

Wonderful project. Thank you for this!

Victor

On 21 Jun 2020, at 15:00, Ross Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:



All I can think of is that you might not be running Python 3 from your console. You could try "python3 file_name" and see if that works.

**Comment by roscoe81** [comment]
Thanks so much for your feedback Victor and fer prompting me to document the Adafruit IO setup. I've has a lot of fun working on this project and the Pimoroni examples on GitHub gave me a great head start.  I'm delighted that you find it valuable

 FYI, I've been working on a User Guide for some time now and I've just published it here: https://github.com/roscoe81/enviro-monitor/blob/master/User%20Guide/Northcliff%20Enviro%20Monitor%20User%20Guide-Gen.pdf

Hope you find it valuable.

**Comment by vschinazi** [comment]
Hi Ross

Thank you for sharing this. I just browsed the manual and this is indeed very helpful. Now I am very  tempted to get a case!
Have great evening!

Victor

On 21 Jun 2020, at 21:50, Ross Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks so much for your feedback Victor and fer prompting me to document the Adafruit IO setup. I've has a lot of fun working on this project and the Pimoroni examples on GitHub gave me a great head start. I'm delighted that you find it valuable

FYI, I've been working on a User Guide for some time now and I've just published it here: https://github.com/roscoe81/enviro-monitor/blob/master/User%20Guide/Northcliff%20Enviro%20Monitor%20User%20Guide-Gen.pdf

Hope you find it valuable.

**Comment by vschinazi** [comment]
Hi Ross

Everything is working great. I just wanted to ask you a question about the case. I wanted to print a case for indoor. I have the Enviro+ monitor and the particle matter sensor. Can you please confirm that I need to print:


1. Northcliff_EM_Base_01.stl
2. Northcliff_EM_Case_01.stl
3. Northcliff_EM_Cover_01.stl
4. Northcliff_EM_Pi_Pins_01.stl

Also, I am new to this 3D printing business. Can you recommend a sire that will do this for a reasonable price? I think you ar din Australia, right?

Thank you,

Victor

On 21 Jun 2020, at 21:50, Ross Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks so much for your feedback Victor and fer prompting me to document the Adafruit IO setup. I've has a lot of fun working on this project and the Pimoroni examples on GitHub gave me a great head start. I'm delighted that you find it valuable

FYI, I've been working on a User Guide for some time now and I've just published it here: https://github.com/roscoe81/enviro-monitor/blob/master/User%20Guide/Northcliff%20Enviro%20Monitor%20User%20Guide-Gen.pdf

Hope you find it valuable.

**Comment by roscoe81** [comment]
Yes Victor, that list of case parts is correct, however you only need the base if you're not mounting the unit on a wall. Also, you only need two pins per unit but the pins file prints eight pins at a time.

I've updated the files today to the my latest versions, so they're now all up to date.

I have no experience with 3D printing services, since I print my own parts but it looks like there are many services operating in Australia.

You'll also need a 40 way ribbon cable and connector assembly to interconnect the Raspberry Pi and the Enviro+. I use a 50 way cable from Jaycar (part number WM4508) cut to a length of 72mm and with 10 wires removed, a 40 way socket from Jaycar (part number PS0989) and a 40 way plug from Mouser (part number 517-4640-6001). The result is as per the photos.

Hope that helps.

![ribbon2](https://user-images.githubusercontent.com/37389643/85254664-28c72f00-b4a4-11ea-8586-b7f9b4dc6641.jpg)
![ribbon1](https://user-images.githubusercontent.com/37389643/85254670-2bc21f80-b4a4-11ea-94a5-fb0f2d3e7fea.jpg)

**Comment by vschinazi** [comment]
Hi Ross

Thank you for this information. I am already using a 40 pin cable for the sensor (see photo attached) so this should be OK (although the cable is a bit long). The prices for 3D printing online are really awful so I will see if I can make a woodbox this coming weekend.

Have a great evening,

Victor

[cid:6251ED06-E0E3-46E3-8C1C-9DF10B086C94@hub]


On 22 Jun 2020, at 16:21, Ross Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:



Yes Victor, that list of case parts is correct, however you only need the base if you're not mounting the unit on a wall. Also, you only need two pins per unit but the pins file prints eight pins at a time.

I've updated the files today to the my latest versions, so they're now all up to date.

I have no experience with 3D printing services, since I print my own parts but it looks like there are many services operating in Australia.

You'll also need a 40 way ribbon cable and connector assembly to interconnect the Raspberry Pi and the Enviro+. I use a 50 way cable from Jaycar (part number WM4508) cut to a length of 72mm and with 10 wires removed, a 40 way socket from Jaycar (part number PS0989) and a 40 way plug from Mouser (part number 517-4640-6001). The result is as per the photos.

Hope that helps.

[ribbon2]<https://user-images.githubusercontent.com/37389643/85254664-28c72f00-b4a4-11ea-8586-b7f9b4dc6641.jpg>
[ribbon1]<https://user-images.githubusercontent.com/37389643/85254670-2bc21f80-b4a4-11ea-94a5-fb0f2d3e7fea.jpg>
